version: '3.9'

services:
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    depends_on:
      - mosquitto
      - mariadb
    environment:
      - SERVICE_NAME=node-red
      - TZ=America/Argentina
    networks:
      - localnet

  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    networks:
      - localnet
    volumes:
      - ./config:/mosquitto/config
      - ./config:/mosquitto/data
      - ./config:/mosquitto/log
    ports:
      - "1883:1883"
  
  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    restart: always
    networks:
      - localnet
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=nodered
      - MYSQL_USER=nodered
      - MYSQL_PASSWORD=password
    volumes:
      - ./mariadb:/var/lib/mysql

volumes:
  config:
  data:
  log:
  node-red-data:
  mariadb_data:

networks:
  localnet: